REGRESSION_CONFIGS = {
    "all": {
        "features": [
            "disaster",
            "economy",
            "emo.anger",
            "emo.anticipation",
            "emo.disgust",
            "emo.fear",
            "emo.joy",
            "emo.sadness",
            "emo.surprise",
            "emo.trust",
            "mfd.vice_authority",
            "mfd.vice_fairness",
            "mfd.vice_harm",
            "mfd.vice_loyalty",
            "mfd.vice_purity",
            "mfd.virtue_authority",
            "mfd.virtue_fairness",
            "mfd.virtue_harm",
            "mfd.virtue_loyalty",
            "mfd.virtue_purity",
            "negation",
            "senti.HAN",
            "senti.HAP",
            "senti.LAN",
            "senti.LAP",
            "senti.NEU",
            "subj.combined",
            "subj.strong",
            "subj.weak",
            "vad.arousal",
            "vad.dominance",
            "vad.valence",
            "vder.compound",
            "vder.neg",
            "vder.neu",
            "vder.pos",
        ],
        "const_bias": True,
        "log_follower_bias": True,
        "target": "log_retweets",
    },
    "vad": {
        "features": [
            "vad.arousal",
            "vad.dominance",
            "vad.valence",
        ],
        "const_bias": True,
        "log_follower_bias": True,
        "target": "log_retweets",
    },
    "no-codep": {
        "features": [
            "disaster",
            "economy",
            "emo.anger",
            "emo.anticipation",
            "emo.disgust",
            "emo.fear",
            "emo.joy",
            "emo.sadness",
            "emo.surprise",
            "emo.trust",
            "mfd.vice_authority",
            "mfd.vice_fairness",
            "mfd.vice_harm",
            "mfd.vice_loyalty",
            "mfd.vice_purity",
            "mfd.virtue_authority",
            "mfd.virtue_fairness",
            "mfd.virtue_harm",
            "mfd.virtue_loyalty",
            "mfd.virtue_purity",
            "negation",
            "senti.HAN",
            "senti.HAP",
            "senti.LAN",
            "senti.LAP",
            "senti.NEU",
            "subj.combined",
            # "subj.strong",
            # "subj.weak",
            "vad.arousal",
            "vad.dominance",
            "vad.valence",
            "vder.compound",
            # "vder.neg",
            # "vder.neu",
            # "vder.pos",
        ],
        "const_bias": True,
        "log_follower_bias": True,
        "target": "log_retweets",
    },
}


def get_regression_config(config_name):
    return REGRESSION_CONFIGS[config_name]
