REGRESSION_CONFIGS = {
    "main": {
        "features": [
            "term.disaster",
            "term.economy",
            "term.negation",
            "term.science",
            "emo.anger",
            "emo.anticipation",
            "emo.disgust",
            "emo.fear",
            "emo.joy",
            "emo.sadness",
            "emo.surprise",
            "emo.trust",
            "mfd.vice_authority",
            "mfd.vice_fairness",
            "mfd.vice_harm",
            "mfd.vice_loyalty",
            "mfd.vice_purity",
            "mfd.virtue_authority",
            "mfd.virtue_fairness",
            "mfd.virtue_harm",
            "mfd.virtue_loyalty",
            "mfd.virtue_purity",
            "senti.HAN",
            "senti.HAP",
            "senti.LAN",
            "senti.LAP",
            "senti.NEU",
            "subj.combined",
            "subj.strong",
            "subj.weak",
            "vad.arousal",
            "vad.dominance",
            "vad.valence",
            # "vder.compound",
            # "vder.neg",
            # "vder.neu",
            # "vder.pos",
        ],
        "const_bias": True,
        "log_follower_bias": True,
        "target": "log_retweets",
    },
    "vad": {
        "features": [
            # "senti.LAN",  # collinear
            "vad.arousal",
            "vad.dominance",
            "vad.valence",
        ],
        "const_bias": True,
        "log_follower_bias": True,
        "target": "log_retweets",
    },
    "vadbin": {
        "features": [
            "vad.dominance.pos",
            "vad.dominance.neu",
            "vad.dominance.neg",
            "vad.arousal.pos",
            "vad.arousal.neu",
            "vad.arousal.neg",
            "vad.valence.pos",
            "vad.valence.neu",
            "vad.valence.neg",
        ],
        "const_bias": True,
        "log_follower_bias": True,
        "target": "log_retweets",
    },
    "vadterm": {
        "features": [
            # "vad.term.valence.pos.*",
            # "vad.term.valence.neg.*",
            "vad.term.arousal.pos.*",
            "vad.term.arousal.neg.*",
            # "vad.term.dominance.pos.*",
            # "vad.term.dominance.neg.*",
        ],
        "const_bias": True,
        "log_follower_bias": True,
        "target": "log_retweets",
    },
    "mfd": {
        "features": [
            # "mfd.virtue_authority",
            "mfd.vice_authority",
            # "mfd.virtue_fairness",
            "mfd.vice_fairness",
            # "mfd.virtue_harm",
            "mfd.vice_harm",
            # "mfd.virtue_loyalty",
            "mfd.vice_loyalty",
            # "mfd.virtue_purity",
            "mfd.vice_purity",
        ],
        "const_bias": True,
        "log_follower_bias": True,
        "target": "log_retweets",
    },
    "mfdterm": {
        "features": [
            # "mfd.virtue_authority.*",
            # "mfd.vice_authority.*",
            # "mfd.virtue_fairness.*",
            # "mfd.vice_fairness.*",
            # "mfd.virtue_harm.*",
            # "mfd.vice_harm.*",
            "mfd.virtue_loyalty.*",
            "mfd.vice_loyalty.*",
            # "mfd.virtue_purity.*",
            # "mfd.vice_purity.*",
        ],
        "const_bias": True,
        "log_follower_bias": True,
        "target": "log_retweets",
    },
    "senti": {
        "features": [
            "senti.HAN",
            "senti.HAP",
            "senti.LAN",
            "senti.LAP",
            "senti.NEU",
        ],
        "const_bias": True,
        "log_follower_bias": True,
        "target": "log_retweets",
    },
    "threat": {
        "features": [
            "term.threat",
        ],
        "const_bias": True,
        "log_follower_bias": True,
        "target": "log_retweets",
    },
    "threatvad": {
        "features": [
            "term.threat",
            "vad.arousal",
            "vad.dominance",
            "vad.valence",
        ],
        "const_bias": True,
        "log_follower_bias": True,
        "target": "log_retweets",
    },
    "threatterms": {
        "features": [
            "term.threat.catastroph",
            "term.threat.crisi",
            "term.threat.danger",
            "term.threat.destroy",
            "term.threat.destruct",
            "term.threat.threat",
            "term.threat.worsen",
            "term.threat.worst",
        ],
        "const_bias": True,
        "log_follower_bias": True,
        "target": "log_retweets",
    },
}


def get_regression_config(config_name):
    return REGRESSION_CONFIGS[config_name]
